name: Performance Test

on:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install k6
      run: sudo apt-get install -y k6

    - name: Run k6 test
      run: k6 run test.js --out json=results.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: k6-results
        path: results.json
